// src/app/alerts/page.tsx
"use client";

import { useQuery } from "convex/react";
import { api } from "../../../convex/_generated/api";
import Link from "next/link";

function getSeverityColor(severity: "low" | "medium" | "high" | "critical") {
  const colors = {
    low: "#22c55e",
    medium: "#f59e0b",
    high: "#ef4444",
    critical: "#a855f7",
  };
  return colors[severity];
}

function formatTime(timestamp: number) {
  const diff = Date.now() - timestamp;
  const minutes = Math.floor(diff / 60000);
  if (minutes < 1) return "Just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

export default function AlertsPage() {
  const alerts = useQuery(api.alerts.listRecent, { limit: 50 });

  return (
    <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)] p-8">
      <div className="max-w-4xl mx-auto">
        {/* Back link */}
        <Link
          href="/"
          className="text-[var(--text-dim)] text-xs tracking-[0.1em] uppercase hover:text-[var(--accent)] transition-colors mb-8 inline-block"
        >
          ← Back
        </Link>

        <header className="flex justify-between items-start pb-6 border-b border-[#1a1a1a] mb-8">
          <div>
            <h1 className="text-2xl font-semibold text-[#fafafa]">⚠ Detection Alerts</h1>
            <p className="mt-2 text-sm text-[#666]">Suspicious trading patterns flagged by Argus</p>
          </div>
          <div className="flex gap-2">
            <select className="px-4 py-2 bg-[#0a0a0a] border border-[#252525] rounded text-[#888] text-xs hover:border-[var(--accent)] hover:text-[var(--accent)] transition-all cursor-pointer">
              <option value="">All Severities</option>
              <option value="critical">Critical</option>
              <option value="high">High</option>
              <option value="medium">Medium</option>
              <option value="low">Low</option>
            </select>
            <select className="px-4 py-2 bg-[#0a0a0a] border border-[#252525] rounded text-[#888] text-xs hover:border-[var(--accent)] hover:text-[var(--accent)] transition-all cursor-pointer">
              <option value="">All Statuses</option>
              <option value="new">New</option>
              <option value="investigating">Investigating</option>
              <option value="confirmed">Confirmed</option>
              <option value="dismissed">Dismissed</option>
            </select>
          </div>
        </header>

        <div className="flex flex-col gap-3">
          {alerts === undefined ? (
            <div className="bg-[#0a0a0a] border border-[#1a1a1a] rounded-lg p-16 text-center">
              <span className="text-3xl text-[var(--accent)] animate-pulse">◉</span>
              <p className="mt-4 text-sm text-[#666]">Loading alerts...</p>
            </div>
          ) : alerts.length === 0 ? (
            <div className="bg-[#0a0a0a] border border-[#1a1a1a] rounded-lg p-16 text-center">
              <span className="text-4xl text-[#333] block mb-4">◎</span>
              <h3 className="text-base text-[#fafafa] mb-2">No alerts detected</h3>
              <p className="text-sm text-[#666]">The agent will create alerts when it detects suspicious trading activity.</p>
            </div>
          ) : (
            alerts.map((alert) => (
              <div
                key={alert._id}
                className="bg-[#0a0a0a] border border-[#1a1a1a] rounded-lg p-5 hover:border-[#252525] hover:bg-[#0f0f0f] transition-all"
              >
                <div className="flex items-center gap-3 mb-3">
                  <span
                    className="px-2 py-1 rounded text-[0.65rem] font-bold uppercase tracking-wider text-white"
                    style={{ backgroundColor: getSeverityColor(alert.severity) }}
                  >
                    {alert.severity}
                  </span>
                  <span className="text-xs text-[#666] capitalize">
                    {alert.signalType.replace(/_/g, " ")}
                  </span>
                  <span
                    className={`ml-auto px-2 py-1 rounded text-[0.65rem] font-semibold uppercase tracking-wider ${
                      alert.status === "new"
                        ? "bg-[rgba(59,130,246,0.15)] text-[#3b82f6]"
                        : alert.status === "investigating"
                        ? "bg-[rgba(245,158,11,0.15)] text-[var(--accent)]"
                        : alert.status === "confirmed"
                        ? "bg-[rgba(239,68,68,0.15)] text-[#ef4444]"
                        : "bg-[rgba(34,197,94,0.15)] text-[#22c55e]"
                    }`}
                  >
                    {alert.status}
                  </span>
                </div>
                <h3 className="text-base font-medium text-[#fafafa] mb-2">{alert.title}</h3>
                <p className="text-sm text-[#666] leading-relaxed mb-3">
                  {alert.evidence.reasoning.slice(0, 150)}...
                </p>
                <div className="flex justify-between items-center pt-3 border-t border-[#1a1a1a] text-xs text-[#444]">
                  <span className="font-mono">
                    <span className="text-[#333]">Account: </span>
                    {alert.accountAddress.slice(0, 6)}...{alert.accountAddress.slice(-4)}
                  </span>
                  <span>{formatTime(alert.createdAt)}</span>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}

// src/routes/alerts/+page.svelte
<script lang="ts">
	import { useQuery } from "convex-svelte";
	import { api } from "../../../convex/_generated/api.js";

	const alertsQuery = useQuery(api.alerts.listRecent, { limit: 50 });

	function getSeverityColor(severity: "low" | "medium" | "high" | "critical") {
		const colors = {
			low: "#22c55e",
			medium: "#f59e0b",
			high: "#ef4444",
			critical: "#a855f7",
		};
		return colors[severity];
	}

	function formatTime(timestamp: number) {
		const diff = Date.now() - timestamp;
		const minutes = Math.floor(diff / 60000);
		if (minutes < 1) return "Just now";
		if (minutes < 60) return `${minutes}m ago`;
		const hours = Math.floor(minutes / 60);
		if (hours < 24) return `${hours}h ago`;
		return `${Math.floor(hours / 24)}d ago`;
	}
</script>

<svelte:head>
	<title>Alerts — Argus</title>
</svelte:head>

<div class="alerts-page">
	<header class="page-header">
		<div class="header-content">
			<h1>⚠ Detection Alerts</h1>
			<p class="subtitle">Suspicious trading patterns flagged by Argus</p>
		</div>
		<div class="filters">
			<select>
				<option value="">All Severities</option>
				<option value="critical">Critical</option>
				<option value="high">High</option>
				<option value="medium">Medium</option>
				<option value="low">Low</option>
			</select>
			<select>
				<option value="">All Statuses</option>
				<option value="new">New</option>
				<option value="investigating">Investigating</option>
				<option value="confirmed">Confirmed</option>
				<option value="dismissed">Dismissed</option>
			</select>
		</div>
	</header>

	<div class="alerts-list">
		{#if $alertsQuery === undefined}
			<div class="loading">
				<span class="loading-eye">◉</span>
				<p>Loading alerts...</p>
			</div>
		{:else if $alertsQuery?.length === 0}
			<div class="empty-state">
				<span class="empty-icon">◎</span>
				<h3>No alerts detected</h3>
				<p>The agent will create alerts when it detects suspicious trading activity.</p>
			</div>
		{:else}
			{#each $alertsQuery ?? [] as alert}
				<a href="/alerts/{alert._id}" class="alert-card">
					<div class="alert-header">
						<span class="severity-badge" style="background-color: {getSeverityColor(alert.severity)}">
							{alert.severity}
						</span>
						<span class="signal-type">{alert.signalType.replace(/_/g, " ")}</span>
						<span class="status-badge {alert.status}">{alert.status}</span>
					</div>
					<h3>{alert.title}</h3>
					<p class="reasoning">{alert.reasoning.slice(0, 150)}...</p>
					<div class="alert-meta">
						<span class="account">
							<span class="label">Account:</span>
							{alert.accountAddress.slice(0, 6)}...{alert.accountAddress.slice(-4)}
						</span>
						<span class="time">{formatTime(alert.createdAt)}</span>
					</div>
				</a>
			{/each}
		{/if}
	</div>
</div>

<style>
	.alerts-page {
		display: flex;
		flex-direction: column;
		gap: 2rem;
	}

	.page-header {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
		padding-bottom: 1.5rem;
		border-bottom: 1px solid #1a1a1a;
	}

	.header-content h1 {
		margin: 0;
		font-size: 1.5rem;
		font-weight: 600;
		color: #fafafa;
	}

	.subtitle {
		margin: 0.5rem 0 0;
		font-size: 0.8rem;
		color: #666;
	}

	.filters {
		display: flex;
		gap: 0.5rem;
	}

	.filters select {
		padding: 0.5rem 1rem;
		background: #0a0a0a;
		border: 1px solid #252525;
		border-radius: 4px;
		color: #888;
		font-family: inherit;
		font-size: 0.75rem;
		cursor: pointer;
		transition: all 0.2s;
	}

	.filters select:hover {
		border-color: #f59e0b;
		color: #f59e0b;
	}

	.alerts-list {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.alert-card {
		background: #0a0a0a;
		border: 1px solid #1a1a1a;
		border-radius: 8px;
		padding: 1.25rem;
		text-decoration: none;
		transition: all 0.2s;
	}

	.alert-card:hover {
		border-color: #252525;
		background: #0f0f0f;
	}

	.alert-header {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		margin-bottom: 0.75rem;
	}

	.severity-badge {
		padding: 0.2rem 0.5rem;
		border-radius: 3px;
		color: white;
		font-size: 0.65rem;
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.signal-type {
		font-size: 0.75rem;
		color: #666;
		text-transform: capitalize;
	}

	.status-badge {
		margin-left: auto;
		padding: 0.2rem 0.5rem;
		border-radius: 3px;
		font-size: 0.65rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.status-badge.new {
		background: rgba(59, 130, 246, 0.15);
		color: #3b82f6;
	}

	.status-badge.investigating {
		background: rgba(245, 158, 11, 0.15);
		color: #f59e0b;
	}

	.status-badge.confirmed {
		background: rgba(239, 68, 68, 0.15);
		color: #ef4444;
	}

	.status-badge.dismissed {
		background: rgba(34, 197, 94, 0.15);
		color: #22c55e;
	}

	.alert-card h3 {
		margin: 0 0 0.5rem;
		color: #fafafa;
		font-size: 1rem;
		font-weight: 500;
	}

	.reasoning {
		margin: 0 0 0.75rem;
		color: #666;
		font-size: 0.8rem;
		line-height: 1.5;
	}

	.alert-meta {
		display: flex;
		justify-content: space-between;
		padding-top: 0.75rem;
		border-top: 1px solid #1a1a1a;
		font-size: 0.75rem;
		color: #444;
	}

	.label {
		color: #333;
	}

	.account {
		font-family: 'JetBrains Mono', monospace;
	}

	.loading,
	.empty-state {
		background: #0a0a0a;
		border: 1px solid #1a1a1a;
		border-radius: 8px;
		padding: 4rem 2rem;
		text-align: center;
	}

	.loading-eye {
		font-size: 2rem;
		color: #f59e0b;
		animation: pulse 2s infinite;
	}

	@keyframes pulse {
		0%, 100% { opacity: 1; }
		50% { opacity: 0.3; }
	}

	.loading p {
		margin: 1rem 0 0;
		color: #666;
		font-size: 0.8rem;
	}

	.empty-icon {
		font-size: 2.5rem;
		color: #333;
		display: block;
		margin-bottom: 1rem;
	}

	.empty-state h3 {
		margin: 0 0 0.5rem;
		color: #fafafa;
		font-size: 1rem;
	}

	.empty-state p {
		margin: 0;
		color: #666;
		font-size: 0.85rem;
	}

	@media (max-width: 640px) {
		.page-header {
			flex-direction: column;
			gap: 1rem;
		}

		.filters {
			width: 100%;
		}

		.filters select {
			flex: 1;
		}
	}
</style>
