// src/app/accounts/page.tsx
"use client";

import { useQuery } from "convex/react";
import { api } from "../../../convex/_generated/api";
import Link from "next/link";

function getRiskColor(score: number) {
  if (score >= 70) return "#f44336";
  if (score >= 40) return "#ff9800";
  return "#4caf50";
}

function shortenAddress(addr: string) {
  return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
}

function formatVolume(vol: number) {
  if (vol >= 1000000) return `$${(vol / 1000000).toFixed(1)}M`;
  if (vol >= 1000) return `$${(vol / 1000).toFixed(0)}K`;
  return `$${vol}`;
}

export default function AccountsPage() {
  const accounts = useQuery(api.accounts.listFlagged, {});

  return (
    <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)] p-8">
      <div className="max-w-6xl mx-auto">
        {/* Back link */}
        <Link
          href="/"
          className="text-[var(--text-dim)] text-xs tracking-[0.1em] uppercase hover:text-[var(--accent)] transition-colors mb-8 inline-block"
        >
          ← Back
        </Link>

        <header className="flex justify-between items-center pb-6 border-b border-[#1a1a1a] mb-8">
          <h1 className="text-2xl font-semibold text-[#fafafa]">Flagged Accounts</h1>
          <select className="px-4 py-2 bg-[#0a0a0a] border border-[#252525] rounded text-[#888] text-xs hover:border-[var(--accent)] hover:text-[var(--accent)] transition-all cursor-pointer">
            <option value="riskScore">Sort by Risk Score</option>
            <option value="volume">Sort by Volume</option>
            <option value="winRate">Sort by Win Rate</option>
          </select>
        </header>

        {accounts === undefined ? (
          <div className="bg-[#0a0a0a] border border-[#1a1a1a] rounded-lg p-16 text-center">
            <span className="text-3xl text-[var(--accent)] animate-pulse">◉</span>
            <p className="mt-4 text-sm text-[#666]">Loading accounts...</p>
          </div>
        ) : accounts.length === 0 ? (
          <div className="bg-[#0a0a0a] border border-[#1a1a1a] rounded-lg p-16 text-center">
            <span className="text-4xl text-[#333] block mb-4">◎</span>
            <h3 className="text-base text-[#fafafa] mb-2">No flagged accounts</h3>
            <p className="text-sm text-[#666]">Accounts will appear here when the agent flags suspicious activity.</p>
          </div>
        ) : (
          <div className="bg-[#0a0a0a] border border-[#1a1a1a] rounded-lg overflow-hidden">
            {/* Table header */}
            <div className="grid grid-cols-[2fr_1fr_0.75fr_1fr_0.75fr_0.75fr] gap-4 px-6 py-4 bg-[#0f0f0f] text-xs font-bold text-[#666] uppercase tracking-wider">
              <span>Account</span>
              <span>Risk Score</span>
              <span>Trades</span>
              <span>Volume</span>
              <span>Win Rate</span>
              <span>Age</span>
            </div>

            {/* Table rows */}
            {accounts.map((account) => (
              <div
                key={account._id}
                className="grid grid-cols-[2fr_1fr_0.75fr_1fr_0.75fr_0.75fr] gap-4 px-6 py-4 items-center border-t border-[#1a1a1a] border-l-[3px] border-l-[#f44336] hover:bg-[#111] transition-colors cursor-pointer"
              >
                <div className="flex flex-col gap-1">
                  <span className="font-mono text-[#fafafa]">{shortenAddress(account.address)}</span>
                  {account.displayName && (
                    <span className="text-xs text-[#666]">{account.displayName}</span>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  <div
                    className="h-2 rounded max-w-[60px]"
                    style={{
                      width: `${account.riskScore}%`,
                      backgroundColor: getRiskColor(account.riskScore),
                    }}
                  />
                  <span className="text-sm">{account.riskScore}</span>
                </div>
                <span className="text-sm">{account.totalTrades ?? 0}</span>
                <span className="text-sm">{formatVolume(account.totalVolume ?? 0)}</span>
                <span className="text-sm">{((account.winRate ?? 0) * 100).toFixed(0)}%</span>
                <span className="text-sm">{account.accountAgeDays ?? "?"} days</span>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// src/routes/accounts/+page.svelte
<script lang="ts">
	import { useQuery } from "convex-svelte";
	import { api } from "../../../convex/_generated/api.js";

	const accountsQuery = useQuery(api.accounts.listFlagged, {});

	function getRiskColor(score: number) {
		if (score >= 70) return "#f44336";
		if (score >= 40) return "#ff9800";
		return "#4caf50";
	}

	function shortenAddress(addr: string) {
		return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
	}

	function formatVolume(vol: number) {
		if (vol >= 1000000) return `$${(vol / 1000000).toFixed(1)}M`;
		if (vol >= 1000) return `$${(vol / 1000).toFixed(0)}K`;
		return `$${vol}`;
	}
</script>

<div class="accounts-page">
	<header class="page-header">
		<h1>Flagged Accounts</h1>
		<div class="filters">
			<select>
				<option value="riskScore">Sort by Risk Score</option>
				<option value="volume">Sort by Volume</option>
				<option value="winRate">Sort by Win Rate</option>
			</select>
		</div>
	</header>

	{#if accountsQuery.isLoading}
		<div class="loading">Loading accounts...</div>
	{:else if accountsQuery.data?.length === 0}
		<div class="empty-state">
			<h3>No flagged accounts</h3>
			<p>Accounts will appear here when the agent flags suspicious activity.</p>
		</div>
	{:else}
		<div class="accounts-table">
			<div class="table-header">
				<span>Account</span>
				<span>Risk Score</span>
				<span>Trades</span>
				<span>Volume</span>
				<span>Win Rate</span>
				<span>Age</span>
			</div>
			{#each accountsQuery.data ?? [] as account}
				<a
					href="/accounts/{account.address}"
					class="table-row flagged"
				>
					<div class="account-cell">
						<span class="address">{shortenAddress(account.address)}</span>
						{#if account.displayName}
							<span class="display-name">{account.displayName}</span>
						{/if}
					</div>
					<div class="risk-cell">
						<div
							class="risk-bar"
							style="width: {account.riskScore}%; background: {getRiskColor(account.riskScore)}"
						></div>
						<span>{account.riskScore}</span>
					</div>
					<span>{account.totalTrades ?? 0}</span>
					<span>{formatVolume(account.totalVolume ?? 0)}</span>
					<span>{((account.winRate ?? 0) * 100).toFixed(0)}%</span>
					<span>{account.accountAgeDays ?? "?"} days</span>
				</a>
			{/each}
		</div>
	{/if}
</div>

<style>
	.accounts-page {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.page-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.page-header h1 {
		margin: 0;
		font-size: 2rem;
		color: #1a1a2e;
	}

	.filters {
		display: flex;
		gap: 1rem;
		align-items: center;
	}

	.filters select {
		padding: 0.5rem 1rem;
		border: 1px solid #ddd;
		border-radius: 4px;
		background: white;
	}

	.accounts-table {
		background: white;
		border-radius: 8px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
		overflow: hidden;
	}

	.table-header {
		display: grid;
		grid-template-columns: 2fr 1fr 0.75fr 1fr 0.75fr 0.75fr;
		gap: 1rem;
		padding: 1rem 1.5rem;
		background: #f5f5f5;
		font-weight: bold;
		font-size: 0.875rem;
		color: #666;
	}

	.table-row {
		display: grid;
		grid-template-columns: 2fr 1fr 0.75fr 1fr 0.75fr 0.75fr;
		gap: 1rem;
		padding: 1rem 1.5rem;
		align-items: center;
		border-top: 1px solid #eee;
		text-decoration: none;
		color: inherit;
		transition: background 0.2s;
	}

	.table-row:hover {
		background: #fafafa;
	}

	.table-row.flagged {
		border-left: 3px solid #f44336;
	}

	.account-cell {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.address {
		font-family: monospace;
		color: #1a1a2e;
	}

	.display-name {
		font-size: 0.875rem;
		color: #666;
	}

	.risk-cell {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.risk-bar {
		height: 8px;
		border-radius: 4px;
		max-width: 60px;
	}

	.loading,
	.empty-state {
		background: white;
		border-radius: 8px;
		padding: 3rem;
		text-align: center;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
	}

	.empty-state h3 {
		margin: 0 0 0.5rem;
		color: #1a1a2e;
	}

	.empty-state p {
		margin: 0;
		color: #666;
	}
</style>
